openapi: 3.0.2

info:
  title: portforlo-server
  version: 0.1.0

servers:
  - url: http://localhost:3000

tags:
    - name: utility
      description: 各種機能のAPI
    - name: auth
    - name: article
      description: 記事を管理するAPI
    - name: articles
      description: 複数の記事を管理するAPI

paths:
  /:
    get:
      tags:
        - utility
      summary: 接続を確認する
      responses:
        '200':
          description: OK
  /article:
    post:
      tags:
        - article
      summary: 記事を投稿する
      security:
        - Bearer: []
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/PostArticle'
        required: true
      responses:
        '200':
          description: OK
  /login:
    post:
      tags:
        - auth
      summary: ownerとしてログインする
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/LoginAsOwner'
        required: true
      responses:
        '200':
          description: OK
  /article/{articleID}:
    get:
      tags:
        - article
      summary: 記事を1つ取得する
      parameters:
        - in: path
          name: articleID
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
    delete:
      tags:
        - article
      summary: 記事を削除する
      security:
        - Bearer: []
      parameters:
        - in: path
          name: articleID
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
    put:
      tags:
        - article
      summary: 記事を更新する
      security:
        - Bearer: []
      parameters:
        - in: path
          name: articleID
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/UpdateArticle'
        required: true
      responses:
        '200':
          description: OK

  /articles:
    get:
      tags:
        - articles
      summary: 複数の記事の要約情報を取得する
      responses:
        '200':
          description: OK
      security:
        - Bearer: []

components:
  schemas:
    PostArticle:
      type: object
      properties:
        title:
          type: string
        subtitle:
          type: string
        body:
          type: string
        tags:
          type: array
          items:
            type: string
        is_public:
          type: boolean
    UpdateArticle:
      type: object
      properties:
        title:
          type: string
        subtitle:
          type: string
        body:
          type: string
        tags:
          type: array
          items:
            type: string
        is_public:
          type: boolean
    LoginAsOwner:
      type: object
      properties:
        name:
          type: string
        passwd:
          type: string
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer